language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update

before_script:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: phpunit
